name       : geckodriver
version    : 0.32.0
release    : 6
source     :
    - https://github.com/mozilla/geckodriver/archive/refs/tags/v0.32.0.tar.gz : 97e10921f615e84c1869fa8e1443810914e285e4675e8e45378b99a95c2d0f14
homepage   : https://github.com/mozilla/geckodriver
license    : MPL-2.0
component  : network.web
summary    : WebDriver for Firefox
description: |
    Proxy for using W3C WebDriver compatible clients to interact with Gecko-based browsers. This program provides the HTTP API described by the WebDriver protocol to communicate with Gecko browsers, such as Firefox. It translates calls into the Marionette remote protocol by acting as a proxy between the local- and remote ends.
networking : yes
builddeps  :
    - cargo
rundeps    :
    - firefox
build      : |
    cargo build --release
install    : |
    install -Dm00755 target/release/geckodriver $installdir/usr/bin/geckodriver
